import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { Providers } from './providers/providers';
import { Inter } from 'next/font/google';
import { Footer } from '@/components/footer';

const montserrat = Inter({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <Providers>
          <div className="h-screen overflow-hidden w-screen flex flex-col">
            <div className="h-full w-full overflow-hidden relative">
              {children}
              <div id="portals" className="z-50"></div>
            </div>
            <Footer></Footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
